export enum EVENT_TOPICS {
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
    RESET_PASSWORD = 'RESET_PASSWORD',
    AUTHORIZE_USER = 'AUTHORIZE_USER',
    ONBOARDING_VERIFY = 'ONBOARDING_VERIFY',
    GET_USER_DETAILS = 'GET_USER_DETAILS',
    GET_COUNTRIES = 'GET_COUNTRIES',
    UPDATE_USER = 'UPDATE_USER'
}